config/routes.rb
Rails.application.routes.draw do
  get 'publics/homes'
  get 'publics/top'
  get '/about' => "public/homes#about"

  root to: "public/homes#top"

scope module: :public do
  get '/customers/my_page' => "customers#show", as: "my_page"
  get '/customers/information/edit' => "customers#edit", as: "information/edit"
  patch '/customers' => "customers#update"
  get '/cutomers/confirm' => "customers#confirm", as: "confirm"
  patch '/customers/unsubscribe' => "customers#unsubscribe", as: "unsubscribe"
  resources :items, only: [:index, :show]
  resources :shipping_addresses, only: [:index, :edit, :update, :create, :destroy]
  delete '/cart_items/destroy_all' => "cart_items#destroy_all"
  resources :cart_items, only: [:index, :create, :update, :destroy]
  post '/orders/confirm' => "orders#confirm"
  get '/orders/thanks' => "orders#thanks"
  resources :orders, only: [:new, :create, :index, :show]
  end


namespace :admin do
    get '/' => "homes#top"
    resources :genres, only: [:index, :edit, :update, :create]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    patch '/orders_details/:id' => "orders_details#update_making", as: "update_making"
  end

  # 顧客用
  # URL /customers/sign_in....
  devise_for :customers, skip:[:passwords], controllers:{
    registrations: "public/registrations" ,
    sessions: 'public/sessions'
  }
  # 管理者用
  # URL /admin/sign_in...
  devise_for :admin, skip:[:registrations, :passwords], controllers:{
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  # 小計を求めるメソッド
  def subtotal
  item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy

  def active_for_authentication?
    super && (is_active == true)
  end

  def full_name
    last_name  + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  # 消費税を求めるメソッド
   def with_tax_price
     (price * 1.1).floor
   end

   def get_item_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
     image.variant(resize_to_limit: [width, height]).processed
   end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait_payment: 0, confirm_payment: 1, in_production: 2, preparing_to_ship: 3, sent: 4 }
  has_many :order_details, dependent: :destroy
   # 消費税を求めるメソッド
   def with_tax_price
     (self.item.price * 1.1).floor
   end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { wait: 0, wait_making: 1, making: 2, making_completed: 3 }
  belongs_to :order
  belongs_to :item
  def subtotal
  item.with_tax_price * quantity
  end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customer = current_customer
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
   if @customer.update(customer_params)
     redirect_to admin_customers_path
   else
     render :edit
   end
  end

 private

  def customer_params
    params.require(:customer).permit(:id, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
  @new_genre= Genre.new
  @genres= Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
  @genre= Genre.new(genre_params)
  @genre.save
  redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

 private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @order = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item= Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
    @genre = @item.genre
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end

 private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status== "confirm_payment"
      OrderDetail.update_all(making_status: "wait_making")
    end
    redirect_to admin_order_path(@order)
  end

 private

  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :postage, :billing_amount, :payment_method, :status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


 def after_sign_in_path_for(resource)
  case resource
   when Admin
    admin_path
   when Customer
    root_path
   else
    root_path
  end
 end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_details_helper.rb
module Admin::OrdersDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/views/admin/customers/edit.html.erb
<div class="p-3  bg-secondary text-white">
<h2><%= @customer.full_name %>さんの会員情報編集</h2>
</div>

<br />
<%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>

<p>会員id<br /><%= @customer.id %></p>
<p>氏名<%= f.text_field :last_name %>
       <%= f.text_field :first_name %>
</p>
<p>フリガナ<%= f.text_field :last_name_kana %>
            <%= f.text_field :first_name_kana %>
 </p>
<p>郵便番号<%= f.text_field :postal_code %></p>
<p>住所<%= f.text_field :address %></p>
<p>電話番号<%= f.text_field :telephone_number %></p>
<p>メールアドレス<%= f.text_field :email %></p>
<p>会員ステータス<%= f.radio_button :is_active, true %>有効
<%= f.radio_button :is_active, false %>退会</p>

<%= f.submit "変更を保存", class: "btn btn-success" %>

<% end %>

app/views/admin/customers/index.html.erb
<div class="p-3  bg-secondary text-white">
<h2>会員一覧</h2>
</div>
<br />
<table class='table table-bordered'>
  <thead>
   <tr>
   <th>会員ID</th>
   <th>氏名</th>
   <th>メールアドレス</th>
   <th>ステータス</th>
   <th colspan="3"></th>
   </tr>
  </thead>
  <tbody>
  <% @customers.each do |customer| %>
   <tr>
   <td><%= customer.id %></td>
   <td>
   <%= link_to admin_customer_path(customer.id) do %>
   <%= customer.full_name %>
   <% end %>
   </td>
   <td><%= customer.email %></td>
   <td><%= customer.is_active ? "有効" : "退会" %></td>
   </tr>
   <% end %>
  </tbody>
</table>

app/views/admin/customers/show.html.erb
<div class="p-3  bg-secondary text-white">
<h2><%= @customer.full_name %>さんの会員詳細</h2>
</div>

<br />
<div>
  <p>会員id<br /><%= @customer.id %></p>
  <p>氏名<br /><%= @customer.full_name %></p>
  <p>フリガナ<br /><%= @customer.last_name_kana + @customer.first_name_kana %></p>
  <p>郵便番号<br /><%= @customer.postal_code %></p>
  <p>住所<br /><%= @customer.address %></p>
  <p>電話番号<br /><%= @customer.telephone_number %></p>
  <p>メールアドレス<br /><%= @customer.email %></p>
  <p>会員ステータス<br /><%= @customer.is_active ? "有効" : "退会" %> </p>
</div>

<%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success" %>

<%= link_to "注文履歴一覧を見る", admin_path, class:"btn btn-primary" %>