config/routes.rb
Rails.application.routes.draw do
  get 'publics/homes'
  get 'publics/top'
  get '/about' => "public/homes#about"

  root to: "public/homes#top"

scope module: :public do
  get '/customers/my_page' => "customers#show", as: "my_page"
  get '/customers/information/edit' => "customers#edit", as: "information/edit"
  patch '/customers' => "customers#update"
  get '/cutomers/confirm' => "customers#confirm", as: "confirm"
  patch '/customers/unsubscribe' => "customers#unsubscribe", as: "unsubscribe"
  resources :items, only: [:index, :show]
  resources :shipping_addresses, only: [:index, :edit, :update, :create, :destroy]
  delete '/cart_items/destroy_all' => "cart_items#destroy_all"
  resources :cart_items, only: [:index, :create, :update, :destroy]
  post '/orders/confirm' => "orders#confirm"
  get '/orders/thanks' => "orders#thanks"
  resources :orders, only: [:new, :create, :index, :show]
  end


namespace :admin do
    get '/' => "homes#top"
    resources :genres, only: [:index, :edit, :update, :create]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    patch '/orders_details/:id' => "orders_details#update_making", as: "update_making"
  end

  # 顧客用
  # URL /customers/sign_in....
  devise_for :customers, skip:[:passwords], controllers:{
    registrations: "public/registrations" ,
    sessions: 'public/sessions'
  }
  # 管理者用
  # URL /admin/sign_in...
  devise_for :admin, skip:[:registrations, :passwords], controllers:{
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  # 小計を求めるメソッド
  def subtotal
  item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy

  def active_for_authentication?
    super && (is_active == true)
  end

  def full_name
    last_name  + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  # 消費税を求めるメソッド
   def with_tax_price
     (price * 1.1).floor
   end

   def get_item_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
     image.variant(resize_to_limit: [width, height]).processed
   end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait_payment: 0, confirm_payment: 1, in_production: 2, preparing_to_ship: 3, sent: 4 }
  has_many :order_details, dependent: :destroy
   # 消費税を求めるメソッド
   def with_tax_price
     (self.item.price * 1.1).floor
   end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { wait: 0, wait_making: 1, making: 2, making_completed: 3 }
  belongs_to :order
  belongs_to :item
  def subtotal
  item.with_tax_price * quantity
  end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
  @new_genre= Genre.new
  @genres= Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
  @genre= Genre.new(genre_params)
  @genre.save
  redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

 private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @order = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item= Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
    @genre = @item.genre
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end

 private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status== "confirm_payment"
      OrderDetail.update_all(making_status: "wait_making")
    end
    redirect_to admin_order_path(@order)
  end

 private

  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :postage, :billing_amount, :payment_method, :status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


 def after_sign_in_path_for(resource)
  case resource
   when Admin
    admin_path
   when Customer
    root_path
   else
    root_path
  end
 end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_details_helper.rb
module Admin::OrdersDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/views/admin/genres/edit.html.erb
<div class="p-3  bg-secondary text-white">
<h2>ジャンル編集</h2>
</div>

<br />
<h3>ジャンル名</h3>
<%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
<%= f.text_field :name %>
<%= f.submit "変更を保存", class: "btn btn-success" %>
<% end %>

app/views/admin/genres/index.html.erb
<div class="p-3  bg-secondary text-white">
<h2>ジャンル一覧・追加</h2>
</div>

<br />
<h3>ジャンル名</h3>
<%= form_with model: @new_genre, url: admin_genres_path, method: :post do |f| %>
<%= f.text_field :name %>
  <%= f.submit '新規登録' , class: "btn btn-success"%>
<% end %>

<br />
  <table class="table table-bordered">
    <tbody>
      <thead>
      <tr>
        <th></th>
        <th>ジャンル</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.name %></td>
        <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
      </tr>
     <% end %>
    </tbody>
  </table>

app/views/admin/items/edit.html.erb
<div class="p-3  bg-secondary text-white">
<h2>商品編集</h2>
</div>

<br />
<div class="text-center">
<%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>

<p>商品画像<br /><%= f.file_field :image, accept: "image/*" %></p>
<p>商品名<br /><%= f.text_field :name %></p>
<p>商品説明<br /><%= f.text_area :introduction %></p>
<p>ジャンル<br /><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %></p>
<p>税抜価格<br /><%= f.text_field :price %>円</p>
<p>販売ステータス<br /><%= f.radio_button :is_active, true %>販売中
<%= f.radio_button :is_active, false %>販売停止中</p>
<%= f.submit "変更を保存", class: "btn btn-success" %>

<% end %>

</div>

app/views/admin/items/index.html.erb
<div class="p-3  bg-secondary text-white">
<h2>商品一覧</h2>
</div>
<br />
<div class="text-right">
  <div class="row">
   <div class="col-md">
<%= link_to "＋", new_admin_item_path, class: "btn btn-secondary btn-lg " %>
<!--rounded-circle p-0-->
</div>
  </div>
   </div>
<br />
<table class='table table-bordered'>
    <tbody>
      <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admin_item_path(item.id) %></td>
        <td><%= item.price %></td>
        <td><%= item.genre.name %></td>
        <td><%= item.is_active ? "販売中" : "販売停止中" %></td>
      </tr>
     <% end %>
    </tbody>
  </table>

  <%= paginate @items %>

app/views/admin/items/new.html.erb
<div class="p-3  bg-secondary text-white">
<h2>商品新規登録</h2>
</div>

<div class="text-center">
<%= form_with model: @item, url: admin_items_path, method: :post do |f| %>

<br />
<div class="field">
<%= f.label "商品画像" %>
<%= f.file_field :image, accept: "image/*" %>
</div>

<div class="field">
<%= f.label "商品名" %>
<%= f.text_field :name %>
</div>

<div class="field">
<%= f.label "商品説明" %>
<%= f.text_area :introduction %>
</div>

<div class="field">
<%= f.label "ジャンル" %>
<%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>
</div>

<div class="field">
<%= f.label "税抜価格" %>
<%= f.text_field :price %>円
</div>

<div class="field">
<%= f.label "販売ステータス" %>
<%= f.radio_button :is_active, true %>販売中
<%= f.radio_button :is_active, false %>販売停止中
</div>

<div class="actions">
<%= f.submit '新規登録' , class: "btn btn-success"%>
</div>

<% end %>

</div>

app/views/admin/items/show.html.erb
<div class="p-3  bg-secondary text-white">
<h2>商品詳細</h2>
</div>

<br />

<div class="text-center">
 <%= image_tag @item.get_item_image(100, 100) %>
  <p>商品名<br /><%= @item.name %></p>
  <p>商品説明<br /><%= @item.introduction %></p>
  <p>ジャンル<br /><%= @item.genre.name %></p>
  <p>税込価格（税抜価格）<br /><%= (@item.price*1.1).to_i %>(<%= @item.price %>)円</p>
  <p>販売ステータス<br /><%= @item.is_active ? "販売中" : "販売停止中" %> </p>

<%= link_to "編集する", edit_admin_item_path, class: "btn btn-success" %>

</div>

app/views/admin/orders/show.html.erb
<div class="p-3  bg-secondary text-white">
<h2>注文履歴詳細</h2>
</div>
<br />
<%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
<p>購入者<%= @order.name %></p>
<p>注文日<%= @order.created_at.strftime("%Y/%m/%d") %></p>
<p>配送先
〒<%= @order.postal_code %>
  <%= @order.address %>
  <%= @order.name %>
</p>
<p>支払方法<%= @order.payment_method_i18n %></p>
<p>注文ステータス<%= f.select :status, Order.statuses_i18n.invert %></p>
<%= f.submit "更新", class: "btn btn-success" %>
<% end %>

<br />
<table class="table table-bordered">
  <thead>
    <th>商品名</th>
    <th>単価（税込）</th>
    <th>数量</th>
    <th>小計</th>
    <th>ステータス</th>
    <th colspan="3"></th>
  </thead>
  <tbody>
    <% sum=0 %>
  <% @order.order_details.each do |order_detail| %>
      <tr>
         <td><%= order_detail.item.name %></td>
        <td><%= order_detail.item.with_tax_price.to_s(:delimited) %></td>
        <td><%= order_detail.quantity %></td>
        <td><%= (order_detail.item.with_tax_price*order_detail.quantity).to_s(:delimited) %></td>
        <% sum+= (order_detail.item.with_tax_price*order_detail.quantity) %>
        <td>
          <%= form_with model: order_detail, url: admin_update_making_path(order_detail.id), method: :patch do |f| %>
            <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
            <%= f.submit "更新", class: "btn btn-success" %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<p>商品合計<%= sum.to_s(:delimited) %>円</p>
<p>送料<%= @order.postage %>円</p>
<p>請求金額合計<%= (sum+@order.postage).to_s(:delimited) %>円</p>