config/routes.rb
Rails.application.routes.draw do
  get 'publics/homes'
  get 'publics/top'
  get '/about' => "public/homes#about"

  root to: "public/homes#top"

scope module: :public do
  get '/customers/my_page' => "customers#show", as: "my_page"
  get '/customers/information/edit' => "customers#edit", as: "information/edit"
  patch '/customers' => "customers#update"
  get '/cutomers/confirm' => "customers#confirm", as: "confirm"
  patch '/customers/unsubscribe' => "customers#unsubscribe", as: "unsubscribe"
  resources :items, only: [:index, :show]
  resources :shipping_addresses, only: [:index, :edit, :update, :create, :destroy]
  delete '/cart_items/destroy_all' => "cart_items#destroy_all"
  resources :cart_items, only: [:index, :create, :update, :destroy]
  post '/orders/confirm' => "orders#confirm"
  get '/orders/thanks' => "orders#thanks"
  resources :orders, only: [:new, :create, :index, :show]
  end


namespace :admin do
    get '/' => "homes#top"
    resources :genres, only: [:index, :edit, :update, :create]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    patch '/orders_details/:id' => "orders_details#update_making", as: "update_making"
  end

  # 顧客用
  # URL /customers/sign_in....
  devise_for :customers, skip:[:passwords], controllers:{
    registrations: "public/registrations" ,
    sessions: 'public/sessions'
  }
  # 管理者用
  # URL /admin/sign_in...
  devise_for :admin, skip:[:registrations, :passwords], controllers:{
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  # 小計を求めるメソッド
  def subtotal
  item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy

  def active_for_authentication?
    super && (is_active == true)
  end

  def full_name
    last_name  + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  # 消費税を求めるメソッド
   def with_tax_price
     (price * 1.1).floor
   end

   def get_item_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
     image.variant(resize_to_limit: [width, height]).processed
   end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait_payment: 0, confirm_payment: 1, in_production: 2, preparing_to_ship: 3, sent: 4 }
  has_many :order_details, dependent: :destroy
   # 消費税を求めるメソッド
   def with_tax_price
     (self.item.price * 1.1).floor
   end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { wait: 0, wait_making: 1, making: 2, making_completed: 3 }
  belongs_to :order
  belongs_to :item
  def subtotal
  item.with_tax_price * quantity
  end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
  @new_genre= Genre.new
  @genres= Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
  @genre= Genre.new(genre_params)
  @genre.save
  redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

 private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @order = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item= Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
    @genre = @item.genre
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end

 private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


 def after_sign_in_path_for(resource)
  case resource
   when Admin
    admin_path
   when Customer
    root_path
   else
    root_path
  end
 end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
      <%= link_to "ながのCAKE", root_path, class: "navber-brand p-3 text-white" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse" id="navbarNavDropdown" style="">
      <ul class="nav navbar-nav navbar-right ml-auto">
      <% if admin_signed_in? %>
      <li>
        <%= link_to "商品一覧", admin_items_path, class: "nav-link" %>
      </li>
      <li>
        <%= link_to "会員一覧", admin_customers_path, class: "nav-link" %>
      </li>
      <li>
        <%= link_to "注文履歴一覧", admin_path, class: "nav-link" %>
      </li>
      <li>
        <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %>
      </li>
       <li>
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link"%>
      </li>
      <% elsif customer_signed_in? %>
      <li>
        <%= link_to "マイページ", my_page_path, class: "nav-link" %>
      </li>
      <li>
        <%= link_to "商品一覧", items_path, class: "nav-link" %>
      </li>
      <li>
        <%= link_to "カート", cart_items_path, class: "nav-link" %>
      </li>
       <li>
        <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% else %>
      <li>
        <%= link_to "商品一覧", items_path, class: "nav-link" %>
      </li>
      <li>
        <%= link_to "新規登録", new_customer_registration_path, class: "nav-link" %>
      </li>
      <li>
        <%= link_to "ログイン" , customer_session_path, class: "nav-link" %>
      </li>
      <li>
      <%= link_to "About", about_path, class: "nav-link" %>
      </li>
      <% end %>
      </ul>
      </div>
      </div>
      </nav>

  <% if customer_signed_in? %>
   <%= 'ようこそ'+ current_customer.full_name + 'さん' %>
   <% end %>

    </header>

    <main>
    <%= yield %>
    </main>

  </body>

</html>